# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18L6Jq_ovdsOBuWdsPUd422BU20m8F9zJ
"""

!unzip health_data.csv.zip

import pandas as pd

data = pd.read_csv("mental_health_wearable_data.csv")
print(data.head())

pd.read_csv("mental_health_wearable_data.csv")

X = data[['Heart_Rate_BPM','Sleep_Duration_Hours','Physical_Activity_Steps','Mood_Rating']]
y = data['Mental_Health_Condition']

# Dataset info
print(data.info())

# Check missing values
print(data.isnull().sum())

# Remove missing rows
data = data.dropna()

print("After cleaning:", data.shape)

X = data[['Heart_Rate_BPM','Sleep_Duration_Hours','Physical_Activity_Steps','Mood_Rating']]
y = data['Mental_Health_Condition']

print(X.head())
print(y.head())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

print("Model training completed")

y_pred = model.predict(X_test)

print(y_pred[:10])

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy)

# Example wearable data
new_data = pd.DataFrame([[72, 98, 1200, 36.5]], columns=['Heart_Rate_BPM','Sleep_Duration_Hours','Physical_Activity_Steps','Mood_Rating'])

prediction = model.predict(new_data)
print("Predicted Health Risk:", prediction[0])

if prediction[0] == "High":
    print("⚠️ High Risk! Immediate attention needed")
elif prediction[0] == "Medium":
    print("⚠️ Medium Risk! Monitor closely")
else:
    print("✅ Low Risk. Normal condition")

# User input function
def predict_risk():
    hr = float(input("Enter Heart Rate: "))
    sleep = float(input("Enter Sleep Duration (hours): "))
    activity = float(input("Enter Physical Activity (steps): "))
    mood = float(input("Enter Mood Rating (1-10): "))

    # Create a DataFrame with the correct column names
    user_data = pd.DataFrame([[hr, sleep, activity, mood]],
                             columns=['Heart_Rate_BPM','Sleep_Duration_Hours','Physical_Activity_Steps','Mood_Rating'])
    result = model.predict(user_data)

    if result[0] == 0:
        print("🟢 Low Health Risk")
    elif result[0] == 1:
        print("🟡 Medium Health Risk")
    else:
        print("🔴 High Health Risk")

# Call function
while True:
    predict_risk()
    again = input("Do you want to check another person? (yes/no): ")
    if again.lower() != 'yes':
        break
